### ISSUE TITLE
Works Before Connect To Frontend

### ISSUE THREAD

**Issue by tjsgh531** [tjsgh531/fastapi_tutorial#1]
## Description

before create fontend, we have to set fastapi files like main.py / database.py / models.py / 

## Tasks

- [x] create main.py
- [x] create DB in PostgreSQL
- [x] create database.py
- [x] create models.py
- [x] create domain(router / crud / schema)

## References

- [ ]( )
