### ISSUE TITLE
Create Front End

### ISSUE THREAD

**Issue by tjsgh531** [tjsgh531/fastapi_tutorial#2]
## Description

create front end by html, css, js and connect to backend, fastapi

## Tasks

- [x] create html , css, js
- [x] show html
- [x] connect css and js to html
- [x] work "get method" -> view at front

## References

- [ wiki docs ]( https://wikidocs.net/176225)
