### ISSUE TITLE
put data in DB

### ISSUE THREAD

**Issue by tjsgh531** [tjsgh531/fastapi_tutorial#3]
## Description

Let's post data at DB

## Tasks

- [x] make data to put in the DB
- [x] create upload method & execute
- [ ] create post html using form tag
- [ ] upload data, created by form tag , to DB

## References

- [ ]( )
